sut:
  
    build: .

    dockerfile: Dockerfile.test

    links: 
       - web
    command: test.sh
web:

    build: .

    dockerfile: Dockerfile

    ports:
      - "8080:80"

    links:
      - db:mysql

    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_PID_FILE: /var/run/apache2.pid 

db:

    image: mariadb

    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret

    ports:
      - "3000:3000"
