# DEFINIMOS EL NOMBRE DEL SERVICIO
web:
	#CONSTRUYE UN DOCKERFILE A PARTIR DEL DIRECTORIO ACTUAL
    build: .

	#LA MAQUINA ANFITRION ESCUCHARA PETICIONES EN EL PUERTO 8080 Y EL CONTENEDOR EN EL PUERTO 80
    ports:
      - "8080:80" 

	#SE ENLAZA CON EL CONTENEDOR DE MARIA DB 
    links:
      - db:mysql

	#INTRODUCE VARIABLES DE ENTORNO PARA APACHE
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_PID_FILE: /var/run/apache2.pid 

	#CREA UN VOLUMEN DESDE EL DIRECTORIO HTML DEL HOST HASTA EL DIRECTORIO "/var/www/app" DEL CONTENEDOR( todo entre comillas siempre )
    volumes:
      - "html:/var/www/app"

# DEFINIMOS EL NOMBRE DEL SERVICIO
db:
	# HACEMOS UN BUILD DE UNA IMAGEN YA CREADA EN EL REGISTRO DE DOCKER Y ESCRIBIMOS EL NOMBRE DE LA IMAGEN
    image: mariadb

	# PARA INTRODUCIR VARIABLES DE ENTORNO PARA MYSQL
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret

	#ESCUCHA EN EL PUERTO 3000 DEL HOST Y EN EL 3000 DEL CONTENEDOR
    ports:
      - "3000:3000"
  
